### PR TITLE
navigator fix (navigator is not defined on server)

### PR DESCRIPTION
**Pull request by KasperGreen**
on express server don`t start

### CODE REVIEW

**Comment by KasperGreen** [comment]
package.json removed

**Comment by KasperGreen** [comment]
thx

**Comment by stefalda** [comment]
I've published the changes to npm...

**Comment by KasperGreen** [comment]
Without package.json?

**Comment by stefalda** [comment]
I restored it

**Comment by KasperGreen** [comment]
Good! `-- react-localization@0.0.8

Very thx!

**Pull request merged**
