### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nightblade9**
Clarify use of `.formatString` (does not modify in-place, returns modified string)

### CODE REVIEW

**Comment by stefalda** [comment]
Hi nightblade9,
I'm not sure  that creating a new property in the strings object is a best practice for using formatString.
It's a function because the parameters can change so it's better to just embed it in the JSX code, don't you think?

**Comment by nightblade9** [comment]
Hi,

Honestly, I am not sure what the best practice is for this. I was hoping to make an "as minimal as possible" change to the README, to hopefully save anyone else reading it from spending an hour trying to figure out how it works.

I agree that embedding in JSX is much better (that's what I'm doing in my project too). If you prefer that, I'll update the README with a single example that showcases this.

**Comment by stefalda** [comment]
Yes, thank you

**Comment by nightblade9** [comment]
How does it look now @stefalda ?

**Comment by stefalda** [comment]
Perfect!
Thanks

**Pull request merged**
