### PR TITLE
Fix server side

### PR DESCRIPTION
**Pull request by jonanderdev**
Simple fix for the Server side rendering issue mentioned here #53

### CODE REVIEW

**Comment by stefalda** [comment]
Sorry but your commit breaks the tests... and in the end it gives the same results as if the navigator object is undefined....

**Comment by jonanderdev** [comment]
@stefalda I don't agree that it gives the same result. It has been tested into a real project with server side rendering, as we needed to adjust it to make it work into a Next.js react application (which has server side rendering). And with this adjustment we avoid the Reference error that the getInterfaceLanguage function used to throw when using the navigator element.

It could be that the testing tool also has the window object as undefined (like the server), so the prepared tests should have that in mind. 

So If this adjustment doesn't work for you please think about finding another, as nowadays there is a big number of react apps that need to have server side rendering, and we want to keep using your cool react-localization lib.

**Comment by stefalda** [comment]
@jonanderdev I see your point.

I’ve no experience with server side rendering, but I’ll try something else... maybe a simple try..catch around the navigator code?

**Comment by stefalda** [comment]
Hi @jonanderdev, your other solution worked... 

Checkout version 0.1.9.

Thanks

Stefano

**Pull request merged**
