### PR TITLE
[FIX] Wrong language on Chrome

### PR DESCRIPTION
**Pull request by henrikra**
The bug is described here: https://github.com/stefalda/react-localization/issues/36

- The thing that fixed that bug was to move checking existence of `navigator.language` as first. 
- added tests cases for this function
- mocked navigator in test file the main code is cleaner :)
- removed `jasmine-es6` since it is not needed and it is [deprecated](https://github.com/vinsonchuong/jasmine-es6/commit/a29a2686b0704e69a301fc81fd53477161d2547d)
- move `getInterfaceLanguage` to own file since it does not use `this` inside function body. This is the reason that it is util. I think some other functions could be moved there too later :D

### CODE REVIEW

**Comment by henrikra** [comment]
@stefalda Please tell me if you have questions for this PR. When this is ready I am going to do tests for the `stringFormat` with React components :)

**Comment by stefalda** [comment]
I was wondering if moving the "utils" part to a different file could lead to the unification with the react-native-localization project...

**Comment by henrikra** [comment]
Hmm when I looked at https://github.com/stefalda/ReactNativeLocalization I did not see react-localization as its dependency?

**Comment by stefalda** [comment]
No unfortunately they are different plugins even if they share 80% of the code...

**Comment by henrikra** [comment]
Hmm have you thought unifying them? If yes what is blocking to use this library as dependecy for RN version of this library?

**Comment by stefalda** [comment]
Because it started the other way around... first the react-native version then this one :-)

It should be feasable anyway...

The only problem is how to check for the interface language, maybe the constructor could accept a method or a class that implements the getLanguageInterface method...

I have to make some tests...

**Comment by henrikra** [comment]
Ahaa so in React Native you check interface language from native side. Otherwise functionality is almost same? Btw I made new PR :D https://github.com/stefalda/react-localization/pull/40

**Comment by stefalda** [comment]
Exactly.

**Pull request merged**
